package business.message;
import java.util.ArrayList;
import java.util.List;

import business.util.CommonsUtil;
import business.util.DataFormat;
public class VOCMessage implements BaseMessage {
    private List<Double> airCurrentList = new ArrayList();
    private List<Double> smokeCurrentList = new ArrayList();
    private List<Double> so2CurrentList = new ArrayList();
    private List<Double> noxCurrentList = new ArrayList();
    private List<Double> coCurrentList = new ArrayList();
    private List<Double> s02CurrentList = new ArrayList();
    private List<Double> s03CurrentList = new ArrayList();
    private List<Double> s04CurrentList = new ArrayList();
    private List<Double> a25002CurrentList = new ArrayList();
    private List<Double> a25003CurrentList = new ArrayList();
    private List<Double> a25005CurrentList = new ArrayList();
    private List<Double> a24088CurrentList = new ArrayList();
    private List<Double> airMinCouList = new ArrayList();
    private List<Double> smokeMinCouList = new ArrayList();
    private List<Double> so2MinCouList = new ArrayList();
    private List<Double> noxMinCouList = new ArrayList();
    private List<Double> coMinCouList = new ArrayList();
    private List<Double> a25002MinCouList = new ArrayList();
    private List<Double> a25003MinCouList = new ArrayList();
    private List<Double> a25005MinCouList = new ArrayList();
    private List<Double> a24088MinCouList = new ArrayList();
    private List<Double> airMinAvgList = new ArrayList();
    private List<Double> smokeMinAvgList = new ArrayList();
    private List<Double> so2MinAvgList = new ArrayList();
    private List<Double> noxMinAvgList = new ArrayList();
    private List<Double> coMinAvgList = new ArrayList();
    private List<Double> s02MinAvgList = new ArrayList();
    private List<Double> s03MinAvgList = new ArrayList();
    private List<Double> s04MinAvgList = new ArrayList();
    private List<Double> a25002MinAvgList = new ArrayList();
    private List<Double> a25003MinAvgList = new ArrayList();
    private List<Double> a25005MinAvgList = new ArrayList();
    private List<Double> a24088MinAvgList = new ArrayList();
    private List<Double> airMinMaxList = new ArrayList();
    private List<Double> smokeMinMaxList = new ArrayList();
    private List<Double> so2MinMaxList = new ArrayList();
    private List<Double> noxMinMaxList = new ArrayList();
    private List<Double> coMinMaxList = new ArrayList();
    private List<Double> s02MinMaxList = new ArrayList();
    private List<Double> s03MinMaxList = new ArrayList();
    private List<Double> s04MinMaxList = new ArrayList();
    private List<Double> a25002MinMaxList = new ArrayList();
    private List<Double> a25003MinMaxList = new ArrayList();
    private List<Double> a25005MinMaxList = new ArrayList();
    private List<Double> a24088MinMaxList = new ArrayList();
    private List<Double> airMinMinList = new ArrayList();
    private List<Double> smokeMinMinList = new ArrayList();
    private List<Double> so2MinMinList = new ArrayList();
    private List<Double> noxMinMinList = new ArrayList();
    private List<Double> coMinMinList = new ArrayList();
    private List<Double> s02MinMinList = new ArrayList();
    private List<Double> s03MinMinList = new ArrayList();
    private List<Double> s04MinMinList = new ArrayList();
    private List<Double> a25002MinMinList = new ArrayList();
    private List<Double> a25003MinMinList = new ArrayList();
    private List<Double> a25005MinMinList = new ArrayList();
    private List<Double> a24088MinMinList = new ArrayList();
    private List<Double> airHourCouList = new ArrayList();
    private List<Double> smokeHourCouList = new ArrayList();
    private List<Double> so2HourCouList = new ArrayList();
    private List<Double> noxHourCouList = new ArrayList();
    private List<Double> coHourCouList = new ArrayList();
    private List<Double> a25002HourCouList = new ArrayList();
    private List<Double> a25003HourCouList = new ArrayList();
    private List<Double> a25005HourCouList = new ArrayList();
    private List<Double> a24088HourCouList = new ArrayList();
    private List<Double> airHourAvgList = new ArrayList();
    private List<Double> smokeHourAvgList = new ArrayList();
    private List<Double> so2HourAvgList = new ArrayList();
    private List<Double> noxHourAvgList = new ArrayList();
    private List<Double> coHourAvgList = new ArrayList();
    private List<Double> s02HourAvgList = new ArrayList();
    private List<Double> s03HourAvgList = new ArrayList();
    private List<Double> s04HourAvgList = new ArrayList();
    private List<Double> a25002HourAvgList = new ArrayList();
    private List<Double> a25003HourAvgList = new ArrayList();
    private List<Double> a25005HourAvgList = new ArrayList();
    private List<Double> a24088HourAvgList = new ArrayList();
    private List<Double> airHourMaxList = new ArrayList();
    private List<Double> smokeHourMaxList = new ArrayList();
    private List<Double> so2HourMaxList = new ArrayList();
    private List<Double> noxHourMaxList = new ArrayList();
    private List<Double> coHourMaxList = new ArrayList();
    private List<Double> s02HourMaxList = new ArrayList();
    private List<Double> s03HourMaxList = new ArrayList();
    private List<Double> s04HourMaxList = new ArrayList();
    private List<Double> a25002HourMaxList = new ArrayList();
    private List<Double> a25003HourMaxList = new ArrayList();
    private List<Double> a25005HourMaxList = new ArrayList();
    private List<Double> a24088HourMaxList = new ArrayList();
    private List<Double> airHourMinList = new ArrayList();
    private List<Double> smokeHourMinList = new ArrayList();
    private List<Double> so2HourMinList = new ArrayList();
    private List<Double> noxHourMinList = new ArrayList();
    private List<Double> coHourMinList = new ArrayList();
    private List<Double> s02HourMinList = new ArrayList();
    private List<Double> s03HourMinList = new ArrayList();
    private List<Double> s04HourMinList = new ArrayList();
    private List<Double> a25002HourMinList = new ArrayList();
    private List<Double> a25003HourMinList = new ArrayList();
    private List<Double> a25005HourMinList = new ArrayList();
    private List<Double> a24088HourMinList = new ArrayList();

    public VOCMessage() {
    }

    public String current() {
        double air = DataFormat.randomData(0, 50, 1);
        double smoke = DataFormat.randomData(5, 30, 0);
        double so2 = DataFormat.randomData(0, 10, 2);
        double nox = DataFormat.randomData(0, 150, 1);
        double co = DataFormat.randomDouble(0, 200, 3);
        double s02 = DataFormat.randomData(0, 100, 2);
        double s03 = DataFormat.randomData(50, 250, 1);
        double s04 = DataFormat.randomData(10000, 20000, 3);
        double a25002 = DataFormat.randomData(0, 1, 3);
        double a25003 = DataFormat.randomData(0, 5, 2);
        double a25005 = DataFormat.randomData(0, 5, 2);
        double a24088 = DataFormat.randomData(0, 100, 3);
        this.airCurrentList.add(air);
        this.smokeCurrentList.add(smoke);
        this.so2CurrentList.add(so2);
        this.noxCurrentList.add(nox);
        this.coCurrentList.add(co);
        this.s02CurrentList.add(s02);
        this.s03CurrentList.add(s03);
        this.s04CurrentList.add(s04);
        this.a25002CurrentList.add(a25002);
        this.a25003CurrentList.add(a25003);
        this.a25005CurrentList.add(a25005);
        this.a24088CurrentList.add(a24088);
        StringBuffer cmd = new StringBuffer("");
        cmd.append("QN=${QN};ST=27;CN=2011;PW=123456;MN=${MN};Flag=4;CP=&&DataTime=${DataTime};");
        cmd.append("A00000-Rtd=" + air + ",A00000-Flag=N;");
        cmd.append("A34013-Rtd=" + smoke + ",A34013-Flag=N;");
        cmd.append("A21026-Rtd=" + so2 + ",A21026-Flag=N,A21026-EFlag=" + DataFormat.randomDeviceState() + ";");
        cmd.append("A21002-Rtd=" + nox + ",A21002-Flag=" + DataFormat.randomFlag() + ",A21002-EFlag=" + DataFormat.randomDeviceState() + ";");
        cmd.append("A21005-Rtd=" + co + ",A21005-Flag=" + DataFormat.randomFlag() + ";");
        cmd.append("A01011-Rtd=" + s02 + ",A01011-Flag=" + DataFormat.randomFlag() + ";");
        cmd.append("A01012-Rtd=" + s03 + ",A01012-Flag=" + DataFormat.randomFlag() + ";");
        cmd.append("A01017-Rtd=" + s04 + ",A01017-Flag=" + DataFormat.randomFlag() + ";");
        cmd.append("A25002-Rtd=" + a25002 + ";");
        cmd.append("A25003-Rtd=" + a25003 + ";");
        cmd.append("A25005-Rtd=" + a25005 + ";");
        cmd.append("A24088-Rtd=" + a24088);
        cmd.append("&&");
        return cmd.toString();
    }

    public String minute() {
        double airCou = CommonsUtil.numberFormat(DataFormat.cou(this.airCurrentList, 1) * 60.0D, 1);
        double airMax = DataFormat.max(this.airCurrentList);
        double airMin = DataFormat.min(this.airCurrentList);
        double airAvg = DataFormat.avg(this.airCurrentList, 1);
        this.airMinCouList.add(airCou);
        this.airMinMaxList.add(airMax);
        this.airMinMinList.add(airMin);
        this.airMinAvgList.add(airAvg);
        this.airCurrentList.clear();
        double smokeCou = CommonsUtil.numberFormat(DataFormat.cou(this.smokeCurrentList, 0) * airCou / 1000.0D / 1000.0D, 0);
        double smokeMax = DataFormat.max(this.smokeCurrentList);
        double smokeMin = DataFormat.min(this.smokeCurrentList);
        double smokeAvg = DataFormat.avg(this.smokeCurrentList, 0);
        this.smokeMinCouList.add(smokeCou);
        this.smokeMinMaxList.add(smokeMax);
        this.smokeMinMinList.add(smokeMin);
        this.smokeMinAvgList.add(smokeAvg);
        this.smokeCurrentList.clear();
        double so2Cou = CommonsUtil.numberFormat(DataFormat.cou(this.so2CurrentList, 2) * airCou / 1000.0D / 1000.0D, 2);
        double so2Max = DataFormat.max(this.so2CurrentList);
        double so2Min = DataFormat.min(this.so2CurrentList);
        double so2Avg = DataFormat.avg(this.so2CurrentList, 2);
        this.so2MinCouList.add(so2Cou);
        this.so2MinMaxList.add(so2Max);
        this.so2MinMinList.add(so2Min);
        this.so2MinAvgList.add(so2Avg);
        this.so2CurrentList.clear();
        double noxCou = CommonsUtil.numberFormat(DataFormat.cou(this.noxCurrentList, 1) * airCou / 1000.0D / 1000.0D, 1);
        double noxMax = DataFormat.max(this.noxCurrentList);
        double noxMin = DataFormat.min(this.noxCurrentList);
        double noxAvg = DataFormat.avg(this.noxCurrentList, 1);
        this.noxMinCouList.add(noxCou);
        this.noxMinMaxList.add(noxMax);
        this.noxMinMinList.add(noxMin);
        this.noxMinAvgList.add(noxAvg);
        this.noxCurrentList.clear();
        double coCou = CommonsUtil.numberFormat(DataFormat.cou(this.coCurrentList, 3) * airCou / 1000.0D / 1000.0D, 3);
        double coMax = DataFormat.max(this.coCurrentList);
        double coMin = DataFormat.min(this.coCurrentList);
        double coAvg = DataFormat.avg(this.coCurrentList, 3);
        this.coMinCouList.add(coCou);
        this.coMinMaxList.add(coMax);
        this.coMinMinList.add(coMin);
        this.coMinAvgList.add(coAvg);
        this.coCurrentList.clear();
        double s02Max = DataFormat.max(this.s02CurrentList);
        double s02Min = DataFormat.min(this.s02CurrentList);
        double s02Avg = DataFormat.avg(this.s02CurrentList, 2);
        this.s02MinMaxList.add(s02Max);
        this.s02MinMinList.add(s02Min);
        this.s02MinAvgList.add(s02Avg);
        this.s02CurrentList.clear();
        double s03Max = DataFormat.max(this.s03CurrentList);
        double s03Min = DataFormat.min(this.s03CurrentList);
        double s03Avg = DataFormat.avg(this.s03CurrentList, 1);
        this.s03MinMaxList.add(s03Max);
        this.s03MinMinList.add(s03Min);
        this.s03MinAvgList.add(s03Avg);
        this.s03CurrentList.clear();
        double s04Max = DataFormat.max(this.s04CurrentList);
        double s04Min = DataFormat.min(this.s04CurrentList);
        double s04Avg = DataFormat.avg(this.s04CurrentList, 3);
        this.s04MinMaxList.add(s04Max);
        this.s04MinMinList.add(s04Min);
        this.s04MinAvgList.add(s04Avg);
        this.s04CurrentList.clear();
        double a25002Cou = CommonsUtil.numberFormat(DataFormat.cou(this.a25002CurrentList, 3) * airCou / 1000.0D / 1000.0D, 3);
        double a25002Max = DataFormat.max(this.a25002CurrentList);
        double a25002Min = DataFormat.min(this.a25002CurrentList);
        double a25002Avg = DataFormat.avg(this.a25002CurrentList, 3);
        this.a25002MinCouList.add(a25002Cou);
        this.a25002MinMaxList.add(a25002Max);
        this.a25002MinMinList.add(a25002Min);
        this.a25002MinAvgList.add(a25002Avg);
        this.a25002CurrentList.clear();
        double a25003Cou = CommonsUtil.numberFormat(DataFormat.cou(this.a25003CurrentList, 3) * airCou / 1000.0D / 1000.0D, 2);
        double a25003Max = DataFormat.max(this.a25003CurrentList);
        double a25003Min = DataFormat.min(this.a25003CurrentList);
        double a25003Avg = DataFormat.avg(this.a25003CurrentList, 2);
        this.a25003MinCouList.add(a25003Cou);
        this.a25003MinMaxList.add(a25003Max);
        this.a25003MinMinList.add(a25003Min);
        this.a25003MinAvgList.add(a25003Avg);
        this.a25003CurrentList.clear();
        double a25005Cou = CommonsUtil.numberFormat(DataFormat.cou(this.a25005CurrentList, 3) * airCou / 1000.0D / 1000.0D, 2);
        double a25005Max = DataFormat.max(this.a25005CurrentList);
        double a25005Min = DataFormat.min(this.a25005CurrentList);
        double a25005Avg = DataFormat.avg(this.a25005CurrentList, 2);
        this.a25005MinCouList.add(a25005Cou);
        this.a25005MinMaxList.add(a25005Max);
        this.a25005MinMinList.add(a25005Min);
        this.a25005MinAvgList.add(a25005Avg);
        this.a25005CurrentList.clear();
        double a24088Cou = CommonsUtil.numberFormat(DataFormat.cou(this.a24088CurrentList, 3) * airCou / 1000.0D / 1000.0D, 3);
        double a24088Max = DataFormat.max(this.a24088CurrentList);
        double a24088Min = DataFormat.min(this.a24088CurrentList);
        double a24088Avg = DataFormat.avg(this.a24088CurrentList, 3);
        this.a24088MinCouList.add(a24088Cou);
        this.a24088MinMaxList.add(a24088Max);
        this.a24088MinMinList.add(a24088Min);
        this.a24088MinAvgList.add(a24088Avg);
        this.a24088CurrentList.clear();
        StringBuffer cmd = new StringBuffer("");
        cmd.append("QN=${QN};ST=27;CN=2051;PW=123456;MN=${MN};Flag=4;CP=&&DataTime=${DataTime};");
        cmd.append("A00000-Cou=" + airCou + ",A00000-Min=" + airMin + ",A00000-Max=" + airMax + ",A00000-Avg=" + airAvg + ",A00000-Flag=N;");
        cmd.append("A34013-Cou=" + smokeCou + ",A34013-Min=" + smokeMin + ",A34013-Max=" + smokeMax + ",A34013-Avg=" + smokeAvg + ",A34013-Flag=N;");
        cmd.append("A21026-Cou=" + so2Cou + ",A21026-Min=" + so2Min + ",A21026-Max=" + so2Max + ",A21026-Avg=" + so2Avg + ",A21026-Flag=N;");
        cmd.append("A21002-Cou=" + noxCou + ",A21002-Min=" + noxMin + ",A21002-Max=" + noxMax + ",A21002-Avg=" + noxAvg + ",A21002-Flag=N;");
        cmd.append("A21005-Cou=" + coCou + ",A21005-Min=" + coMin + ",A21005-Max=" + coMax + ",A21005-Avg=" + coAvg + ",A21005-Flag=N;");
        cmd.append("A01011-Min=" + s02Min + ",A01011-Max=" + s02Max + ",A01011-Avg=" + s02Avg + ";");
        cmd.append("A01012-Min=" + s03Min + ",A01012-Max=" + s03Max + ",A01012-Avg=" + s03Avg + ";");
        cmd.append("A01017-Min=" + s04Min + ",A01017-Max=" + s04Max + ",A01017-Avg=" + s04Avg + ";");
        cmd.append("A25002-Cou=" + a25002Cou + ",A25002-Min=" + a25002Min + ",A25002-Max=" + a25002Max + ",A25002-Avg=" + a25002Avg + ";");
        cmd.append("A25003-Cou=" + a25003Cou + ",A25003-Min=" + a25003Min + ",A25003-Max=" + a25003Max + ",A25003-Avg=" + a25003Avg + ";");
        cmd.append("A25005-Cou=" + a25005Cou + ",A25005-Min=" + a25005Min + ",A25005-Max=" + a25005Max + ",A25005-Avg=" + a25005Avg + ";");
        cmd.append("A24088-Cou=" + a24088Cou + ",A24088-Min=" + a24088Min + ",A24088-Max=" + a24088Max + ",A24088-Avg=" + a24088Avg);
        cmd.append("&&");
        return cmd.toString();
    }

    public String hour() {
        double airCou = DataFormat.cou(this.airMinCouList, 1);
        double airMax = DataFormat.max(this.airMinMaxList);
        double airMin = DataFormat.min(this.airMinMinList);
        double airAvg = DataFormat.avg(this.airMinAvgList, 1);
        this.airHourCouList.add(airCou);
        this.airHourMaxList.add(airMax);
        this.airHourMinList.add(airMin);
        this.airHourAvgList.add(airAvg);
        this.airMinCouList.clear();
        this.airMinMaxList.clear();
        this.airMinMinList.clear();
        this.airMinAvgList.clear();
        double smokeCou = DataFormat.cou(this.smokeMinCouList, 0);
        double smokeMax = DataFormat.max(this.smokeMinMaxList);
        double smokeMin = DataFormat.min(this.smokeMinMinList);
        double smokeAvg = DataFormat.avg(this.smokeMinAvgList, 0);
        this.smokeHourCouList.add(smokeCou);
        this.smokeHourMaxList.add(smokeMax);
        this.smokeHourMinList.add(smokeMin);
        this.smokeHourAvgList.add(smokeAvg);
        this.smokeMinCouList.clear();
        this.smokeMinMaxList.clear();
        this.smokeMinMinList.clear();
        this.smokeMinAvgList.clear();
        double so2Cou = DataFormat.cou(this.so2MinCouList, 2);
        double so2Max = DataFormat.max(this.so2MinMaxList);
        double so2Min = DataFormat.min(this.so2MinMinList);
        double so2Avg = DataFormat.avg(this.so2MinAvgList, 2);
        this.so2HourCouList.add(so2Cou);
        this.so2HourMaxList.add(so2Max);
        this.so2HourMinList.add(so2Min);
        this.so2HourAvgList.add(so2Avg);
        this.so2MinCouList.clear();
        this.so2MinMaxList.clear();
        this.so2MinMinList.clear();
        this.so2MinAvgList.clear();
        double noxCou = DataFormat.cou(this.noxMinCouList, 1);
        double noxMax = DataFormat.max(this.noxMinMaxList);
        double noxMin = DataFormat.min(this.noxMinMinList);
        double noxAvg = DataFormat.avg(this.noxMinAvgList, 1);
        this.noxHourCouList.add(noxCou);
        this.noxHourMaxList.add(noxMax);
        this.noxHourMinList.add(noxMin);
        this.noxHourAvgList.add(noxAvg);
        this.noxMinCouList.clear();
        this.noxMinMaxList.clear();
        this.noxMinMinList.clear();
        this.noxMinAvgList.clear();
        double coCou = DataFormat.cou(this.coMinCouList, 3);
        double coMax = DataFormat.max(this.coMinMaxList);
        double coMin = DataFormat.min(this.coMinMinList);
        double coAvg = DataFormat.avg(this.coMinAvgList, 3);
        this.coHourCouList.add(coCou);
        this.coHourMaxList.add(coMax);
        this.coHourMinList.add(coMin);
        this.coHourAvgList.add(coAvg);
        this.coMinCouList.clear();
        this.coMinMaxList.clear();
        this.coMinMinList.clear();
        this.coMinAvgList.clear();
        double s02Max = DataFormat.max(this.s02MinMaxList);
        double s02Min = DataFormat.min(this.s02MinMinList);
        double s02Avg = DataFormat.avg(this.s02MinAvgList, 2);
        this.s02HourMaxList.add(s02Max);
        this.s02HourMinList.add(s02Min);
        this.s02HourAvgList.add(s02Avg);
        this.s02MinMaxList.clear();
        this.s02MinMinList.clear();
        this.s02MinAvgList.clear();
        double s03Max = DataFormat.max(this.s03MinMaxList);
        double s03Min = DataFormat.min(this.s03MinMinList);
        double s03Avg = DataFormat.avg(this.s03MinAvgList, 1);
        this.s03HourMaxList.add(s03Max);
        this.s03HourMinList.add(s03Min);
        this.s03HourAvgList.add(s03Avg);
        this.s03MinMaxList.clear();
        this.s03MinMinList.clear();
        this.s03MinAvgList.clear();
        double s04Max = DataFormat.max(this.s04MinMaxList);
        double s04Min = DataFormat.min(this.s04MinMinList);
        double s04Avg = DataFormat.avg(this.s04MinAvgList, 3);
        this.s04HourMaxList.add(s04Max);
        this.s04HourMinList.add(s04Min);
        this.s04HourAvgList.add(s04Avg);
        this.s04MinMaxList.clear();
        this.s04MinMinList.clear();
        this.s04MinAvgList.clear();
        double a25002Cou = DataFormat.cou(this.a25002MinCouList, 3);
        double a25002Max = DataFormat.max(this.a25002MinMaxList);
        double a25002Min = DataFormat.min(this.a25002MinMinList);
        double a25002Avg = DataFormat.avg(this.a25002MinAvgList, 3);
        this.a25002HourCouList.add(a25002Cou);
        this.a25002HourMaxList.add(a25002Max);
        this.a25002HourMinList.add(a25002Min);
        this.a25002HourAvgList.add(a25002Avg);
        this.a25002MinCouList.clear();
        this.a25002MinMaxList.clear();
        this.a25002MinMinList.clear();
        this.a25002MinAvgList.clear();
        double a25003Cou = DataFormat.cou(this.a25003MinCouList, 2);
        double a25003Max = DataFormat.max(this.a25003MinMaxList);
        double a25003Min = DataFormat.min(this.a25003MinMinList);
        double a25003Avg = DataFormat.avg(this.a25003MinAvgList, 2);
        this.a25003HourCouList.add(a25003Cou);
        this.a25003HourMaxList.add(a25003Max);
        this.a25003HourMinList.add(a25003Min);
        this.a25003HourAvgList.add(a25003Avg);
        this.a25003MinCouList.clear();
        this.a25003MinMaxList.clear();
        this.a25003MinMinList.clear();
        this.a25003MinAvgList.clear();
        double a25005Cou = DataFormat.cou(this.a25005MinCouList, 2);
        double a25005Max = DataFormat.max(this.a25005MinMaxList);
        double a25005Min = DataFormat.min(this.a25005MinMinList);
        double a25005Avg = DataFormat.avg(this.a25005MinAvgList, 2);
        this.a25005HourCouList.add(a25005Cou);
        this.a25005HourMaxList.add(a25005Max);
        this.a25005HourMinList.add(a25005Min);
        this.a25005HourAvgList.add(a25005Avg);
        this.a25005MinCouList.clear();
        this.a25005MinMaxList.clear();
        this.a25005MinMinList.clear();
        this.a25005MinAvgList.clear();
        double a24088Cou = DataFormat.cou(this.a24088MinCouList, 3);
        double a24088Max = DataFormat.max(this.a24088MinMaxList);
        double a24088Min = DataFormat.min(this.a24088MinMinList);
        double a24088Avg = DataFormat.avg(this.a24088MinAvgList, 3);
        this.a24088HourCouList.add(a24088Cou);
        this.a24088HourMaxList.add(a24088Max);
        this.a24088HourMinList.add(a24088Min);
        this.a24088HourAvgList.add(a24088Avg);
        this.a24088MinCouList.clear();
        this.a24088MinMaxList.clear();
        this.a24088MinMinList.clear();
        this.a24088MinAvgList.clear();
        StringBuffer cmd = new StringBuffer("");
        cmd.append("QN=${QN};ST=27;CN=2061;PW=123456;MN=${MN};Flag=4;CP=&&DataTime=${DataTime};");
        cmd.append("A00000-Cou=" + airCou + ",A00000-Min=" + airMin + ",A00000-Max=" + airMax + ",A00000-Avg=" + airAvg + ",A00000-Flag=N;");
        cmd.append("A34013-Cou=" + smokeCou + ",A34013-Min=" + smokeMin + ",A34013-Max=" + smokeMax + ",A34013-Avg=" + smokeAvg + ",A34013-Flag=N;");
        cmd.append("A21026-Cou=" + so2Cou + ",A21026-Min=" + so2Min + ",A21026-Max=" + so2Max + ",A21026-Avg=" + so2Avg + ",A21026-Flag=N;");
        cmd.append("A21002-Cou=" + noxCou + ",A21002-Min=" + noxMin + ",A21002-Max=" + noxMax + ",A21002-Avg=" + noxAvg + ",A21002-Flag=N;");
        cmd.append("A21005-Cou=" + coCou + ",A21005-Min=" + coMin + ",A21005-Max=" + coMax + ",A21005-Avg=" + coAvg + ",A21005-Flag=N;");
        cmd.append("A01011-Min=" + s02Min + ",A01011-Max=" + s02Max + ",A01011-Avg=" + s02Avg + ";");
        cmd.append("A01012-Min=" + s03Min + ",A01012-Max=" + s03Max + ",A01012-Avg=" + s03Avg + ";");
        cmd.append("A01017-Min=" + s04Min + ",A01017-Max=" + s04Max + ",A01017-Avg=" + s04Avg + ";");
        cmd.append("A25002-Cou=" + a25002Cou + ",A25002-Min=" + a25002Min + ",A25002-Max=" + a25002Max + ",A25002-Avg=" + a25002Avg + ";");
        cmd.append("A25003-Cou=" + a25003Cou + ",A25003-Min=" + a25003Min + ",A25003-Max=" + a25003Max + ",A25003-Avg=" + a25003Avg + ";");
        cmd.append("A25005-Cou=" + a25005Cou + ",A25005-Min=" + a25005Min + ",A25005-Max=" + a25005Max + ",A25005-Avg=" + a25005Avg + ";");
        cmd.append("A24088-Cou=" + a24088Cou + ",A24088-Min=" + a24088Min + ",A24088-Max=" + a24088Max + ",A24088-Avg=" + a24088Avg);
        cmd.append("&&");
        return cmd.toString();
    }

    public String day() {
        double airCou = DataFormat.cou(this.airHourCouList, 1);
        double airMax = DataFormat.max(this.airHourMaxList);
        double airMin = DataFormat.min(this.airHourMinList);
        double airAvg = DataFormat.avg(this.airHourAvgList, 1);
        this.airHourCouList.clear();
        this.airHourMaxList.clear();
        this.airHourMinList.clear();
        this.airHourAvgList.clear();
        double smokeCou = DataFormat.cou(this.smokeHourCouList, 0);
        double smokeMax = DataFormat.max(this.smokeHourMaxList);
        double smokeMin = DataFormat.min(this.smokeHourMinList);
        double smokeAvg = DataFormat.avg(this.smokeHourAvgList, 0);
        this.smokeHourCouList.clear();
        this.smokeHourMaxList.clear();
        this.smokeHourMinList.clear();
        this.smokeHourAvgList.clear();
        double so2Cou = DataFormat.cou(this.so2HourCouList, 2);
        double so2Max = DataFormat.max(this.so2HourMaxList);
        double so2Min = DataFormat.min(this.so2HourMinList);
        double so2Avg = DataFormat.avg(this.so2HourAvgList, 2);
        this.so2HourCouList.clear();
        this.so2HourMaxList.clear();
        this.so2HourMinList.clear();
        this.so2HourAvgList.clear();
        double noxCou = DataFormat.cou(this.noxHourCouList, 1);
        double noxMax = DataFormat.max(this.noxHourMaxList);
        double noxMin = DataFormat.min(this.noxHourMinList);
        double noxAvg = DataFormat.avg(this.noxHourAvgList, 1);
        this.noxHourCouList.clear();
        this.noxHourMaxList.clear();
        this.noxHourMinList.clear();
        this.noxHourAvgList.clear();
        double coCou = DataFormat.cou(this.coHourCouList, 3);
        double coMax = DataFormat.max(this.coHourMaxList);
        double coMin = DataFormat.min(this.coHourMinList);
        double coAvg = DataFormat.avg(this.coHourAvgList, 3);
        this.coHourCouList.clear();
        this.coHourMaxList.clear();
        this.coHourMinList.clear();
        this.coHourAvgList.clear();
        double s02Max = DataFormat.max(this.s02HourMaxList);
        double s02Min = DataFormat.min(this.s02HourMinList);
        double s02Avg = DataFormat.avg(this.s02HourAvgList, 2);
        this.s02HourMaxList.clear();
        this.s02HourMinList.clear();
        this.s02HourAvgList.clear();
        double s03Max = DataFormat.max(this.s03HourMaxList);
        double s03Min = DataFormat.min(this.s03HourMinList);
        double s03Avg = DataFormat.avg(this.s03HourAvgList, 1);
        this.s03HourMaxList.clear();
        this.s03HourMinList.clear();
        this.s03HourAvgList.clear();
        double s04Max = DataFormat.max(this.s04HourMaxList);
        double s04Min = DataFormat.min(this.s04HourMinList);
        double s04Avg = DataFormat.avg(this.s04HourAvgList, 3);
        this.s04HourMaxList.clear();
        this.s04HourMinList.clear();
        this.s04HourAvgList.clear();
        double a25002Cou = DataFormat.cou(this.a25002HourCouList, 3);
        double a25002Max = DataFormat.max(this.a25002HourMaxList);
        double a25002Min = DataFormat.min(this.a25002HourMinList);
        double a25002Avg = DataFormat.avg(this.a25002HourAvgList, 3);
        this.a25002HourCouList.clear();
        this.a25002HourMaxList.clear();
        this.a25002HourMinList.clear();
        this.a25002HourAvgList.clear();
        double a25003Cou = DataFormat.cou(this.a25003HourCouList, 2);
        double a25003Max = DataFormat.max(this.a25003HourMaxList);
        double a25003Min = DataFormat.min(this.a25003HourMinList);
        double a25003Avg = DataFormat.avg(this.a25003HourAvgList, 2);
        this.a25003HourCouList.clear();
        this.a25003HourMaxList.clear();
        this.a25003HourMinList.clear();
        this.a25003HourAvgList.clear();
        double a25005Cou = DataFormat.cou(this.a25005HourCouList, 2);
        double a25005Max = DataFormat.max(this.a25005HourMaxList);
        double a25005Min = DataFormat.min(this.a25005HourMinList);
        double a25005Avg = DataFormat.avg(this.a25005HourAvgList, 2);
        this.a25005HourCouList.clear();
        this.a25005HourMaxList.clear();
        this.a25005HourMinList.clear();
        this.a25005HourAvgList.clear();
        double a24088Cou = DataFormat.cou(this.a24088HourCouList, 3);
        double a24088Max = DataFormat.max(this.a24088HourMaxList);
        double a24088Min = DataFormat.min(this.a24088HourMinList);
        double a24088Avg = DataFormat.avg(this.a24088HourAvgList, 3);
        this.a24088HourCouList.clear();
        this.a24088HourMaxList.clear();
        this.a24088HourMinList.clear();
        this.a24088HourAvgList.clear();
        StringBuffer cmd = new StringBuffer("");
        cmd.append("QN=${QN};ST=27;CN=2031;PW=123456;MN=${MN};Flag=4;CP=&&DataTime=${DataTime};");
        cmd.append("A00000-Cou=" + airCou + ",A00000-Min=" + airMin + ",A00000-Max=" + airMax + ",A00000-Avg=" + airAvg + ",A00000-Flag=N;");
        cmd.append("A34013-Cou=" + smokeCou + ",A34013-Min=" + smokeMin + ",A34013-Max=" + smokeMax + ",A34013-Avg=" + smokeAvg + ",A34013-Flag=N;");
        cmd.append("A21026-Cou=" + so2Cou + ",A21026-Min=" + so2Min + ",A21026-Max=" + so2Max + ",A21026-Avg=" + so2Avg + ",A21026-Flag=N;");
        cmd.append("A21002-Cou=" + noxCou + ",A21002-Min=" + noxMin + ",A21002-Max=" + noxMax + ",A21002-Avg=" + noxAvg + ",A21002-Flag=N;");
        cmd.append("A21005-Cou=" + coCou + ",A21005-Min=" + coMin + ",A21005-Max=" + coMax + ",A21005-Avg=" + coAvg + ",A21005-Flag=N;");
        cmd.append("A01011-Min=" + s02Min + ",A01011-Max=" + s02Max + ",A01011-Avg=" + s02Avg + ";");
        cmd.append("A01012-Min=" + s03Min + ",A01012-Max=" + s03Max + ",A01012-Avg=" + s03Avg + ";");
        cmd.append("A01017-Min=" + s04Min + ",A01017-Max=" + s04Max + ",A01017-Avg=" + s04Avg + ";");
        cmd.append("A25002-Cou=" + a25002Cou + ",A25002-Min=" + a25002Min + ",A25002-Max=" + a25002Max + ",A25002-Avg=" + a25002Avg + ";");
        cmd.append("A25003-Cou=" + a25003Cou + ",A25003-Min=" + a25003Min + ",A25003-Max=" + a25003Max + ",A25003-Avg=" + a25003Avg + ";");
        cmd.append("A25005-Cou=" + a25005Cou + ",A25005-Min=" + a25005Min + ",A25005-Max=" + a25005Max + ",A25005-Avg=" + a25005Avg + ";");
        cmd.append("A24088-Cou=" + a24088Cou + ",A24088-Min=" + a24088Min + ",A24088-Max=" + a24088Max + ",A24088-Avg=" + a24088Avg);
        cmd.append("&&");
        return cmd.toString();
    }

    private double getZs(double rtd) {
        double zs = rtd * 0.5555555555555556D;
        return CommonsUtil.numberFormat(zs, 3);
    }
}